-- Table for storing the weekly total amount and its 30% of amount
-- Aligned with Sentinel Agent expectations and user requirements
CREATE TABLE IF NOT EXISTS weekly_insights (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    week_start DATE NOT NULL,
    
    -- Backend Agent Fields
    avg_balance NUMERIC(15, 2) NOT NULL,
    min_balance NUMERIC(15, 2) NOT NULL,
    surplus_estimate NUMERIC(15, 2) NOT NULL,
    
    -- User Requested Fields
    total_amount NUMERIC(15, 2) NOT NULL, -- Mapped to avg_balance
    surplus_30_percent NUMERIC(15, 2) NOT NULL, -- 30% of avg_balance
    
    analysis_text TEXT, -- Insights generated by Agent 1 (Sentinel)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, week_start)
);
