export interface Stock {
  symbol: string;
  name: string;
  price: number;
  change: number;
  sector: string;
}

export const MOCK_STOCKS: Stock[] = [
  { symbol: "AAPL", name: "Apple Inc.", price: 182.63, change: 1.25, sector: "Technology" },
  { symbol: "MSFT", name: "Microsoft Corp.", price: 415.10, change: 0.85, sector: "Technology" },
  { symbol: "GOOGL", name: "Alphabet Inc.", price: 142.65, change: -0.45, sector: "Technology" },
  { symbol: "AMZN", name: "Amazon.com Inc.", price: 175.35, change: 2.15, sector: "Consumer Cyclical" },
  { symbol: "TSLA", name: "Tesla Inc.", price: 193.57, change: -3.20, sector: "Consumer Cyclical" },
  { symbol: "NVDA", name: "NVIDIA Corp.", price: 875.28, change: 4.50, sector: "Technology" },
  { symbol: "META", name: "Meta Platforms Inc.", price: 505.95, change: 1.10, sector: "Communication Services" },
  { symbol: "BRK.B", name: "Berkshire Hathaway", price: 408.20, change: 0.15, sector: "Financial Services" },
  { symbol: "V", name: "Visa Inc.", price: 282.45, change: 0.35, sector: "Financial Services" },
  { symbol: "JPM", name: "JPMorgan Chase & Co.", price: 188.50, change: -0.25, sector: "Financial Services" },
  { symbol: "UNH", name: "UnitedHealth Group", price: 485.20, change: -1.05, sector: "Healthcare" },
  { symbol: "MA", name: "Mastercard Inc.", price: 475.30, change: 0.45, sector: "Financial Services" },
  { symbol: "PG", name: "Procter & Gamble", price: 162.15, change: 0.05, sector: "Consumer Defensive" },
  { symbol: "HD", name: "Home Depot Inc.", price: 385.40, change: 0.95, sector: "Consumer Cyclical" },
  { symbol: "COST", name: "Costco Wholesale", price: 725.60, change: 1.20, sector: "Consumer Defensive" },
  { symbol: "ABBV", name: "AbbVie Inc.", price: 178.45, change: -0.35, sector: "Healthcare" },
  { symbol: "MRK", name: "Merck & Co.", price: 128.90, change: 0.25, sector: "Healthcare" },
  { symbol: "CVX", name: "Chevron Corp.", price: 155.30, change: -0.85, sector: "Energy" },
  { symbol: "XOM", name: "Exxon Mobil Corp.", price: 112.45, change: -0.65, sector: "Energy" },
  { symbol: "PEP", name: "PepsiCo Inc.", price: 172.50, change: 0.15, sector: "Consumer Defensive" },
  { symbol: "KO", name: "Coca-Cola Co.", price: 60.25, change: -0.10, sector: "Consumer Defensive" },
  { symbol: "ADBE", name: "Adobe Inc.", price: 525.40, change: -2.15, sector: "Technology" },
  { symbol: "CRM", name: "Salesforce Inc.", price: 305.20, change: 0.75, sector: "Technology" },
  { symbol: "AMD", name: "Advanced Micro Devices", price: 190.45, change: 3.85, sector: "Technology" },
  { symbol: "NFLX", name: "Netflix Inc.", price: 605.30, change: 1.45, sector: "Communication Services" },
  { symbol: "INTC", name: "Intel Corp.", price: 44.25, change: -1.25, sector: "Technology" },
  { symbol: "CSCO", name: "Cisco Systems", price: 48.90, change: 0.15, sector: "Technology" },
  { symbol: "ORCL", name: "Oracle Corp.", price: 125.60, change: 0.95, sector: "Technology" },
  { symbol: "WMT", name: "Walmart Inc.", price: 60.45, change: 0.35, sector: "Consumer Defensive" },
  { symbol: "DIS", name: "Walt Disney Co.", price: 112.30, change: 1.15, sector: "Communication Services" },
  { symbol: "PYPL", name: "PayPal Holdings", price: 62.45, change: -0.85, sector: "Financial Services" },
  { symbol: "SQ", name: "Block Inc.", price: 78.20, change: 2.45, sector: "Technology" },
  { symbol: "UBER", name: "Uber Technologies", price: 75.60, change: 1.95, sector: "Technology" },
  { symbol: "ABNB", name: "Airbnb Inc.", price: 162.45, change: 0.75, sector: "Consumer Cyclical" },
  { symbol: "SHOP", name: "Shopify Inc.", price: 78.90, change: -1.45, sector: "Technology" },
  { symbol: "T", name: "AT&T Inc.", price: 17.25, change: 0.05, sector: "Communication Services" },
  { symbol: "VZ", name: "Verizon Communications", price: 40.15, change: -0.15, sector: "Communication Services" },
  { symbol: "PFE", name: "Pfizer Inc.", price: 27.45, change: -0.45, sector: "Healthcare" },
  { symbol: "NKE", name: "NIKE Inc.", price: 102.30, change: 0.65, sector: "Consumer Cyclical" },
  { symbol: "SBUX", name: "Starbucks Corp.", price: 92.45, change: -0.35, sector: "Consumer Cyclical" },
  { symbol: "MCD", name: "McDonald's Corp.", price: 285.60, change: 0.25, sector: "Consumer Cyclical" },
  { symbol: "BA", name: "Boeing Co.", price: 185.40, change: -2.45, sector: "Industrials" },
  { symbol: "GE", name: "General Electric", price: 165.20, change: 1.15, sector: "Industrials" },
  { symbol: "CAT", name: "Caterpillar Inc.", price: 345.60, change: 0.85, sector: "Industrials" },
  { symbol: "GS", name: "Goldman Sachs Group", price: 395.20, change: 0.45, sector: "Financial Services" },
  { symbol: "MS", name: "Morgan Stanley", price: 88.45, change: -0.15, sector: "Financial Services" },
  { symbol: "IBM", name: "IBM Corp.", price: 192.30, change: 0.65, sector: "Technology" },
  { symbol: "ORCL", name: "Oracle Corp.", price: 128.45, change: 1.25, sector: "Technology" },
  { symbol: "TXN", name: "Texas Instruments", price: 172.60, change: -0.35, sector: "Technology" },
  { symbol: "QCOM", name: "Qualcomm Inc.", price: 168.20, change: 1.45, sector: "Technology" },
];
